name: 'puppet-parser-validate-action'
author: 'eXo Platform <https://github.com/exo-actions/> forked from irasnyd'
description: 'GitHub Action to run "puppet parser validate" syntax check'
inputs:
  args:
    description: 'Path to Puppet manifest files or directory to validate'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'share-2'
  color: 'orange'
